### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by JACKYLUO1991** [huangyangyi/ELICIT#2]
The training process often shows 100% GPU utilization and the code gets stuck... Also, the model is very poor for hand rendering, is there a better suggestion?

**Comment by huangyangyi** [comment]
For the stuck problem, please make sure that you have sufficient GPU memory and a compatible environment. We use 4 NVIDIA V100 GPUs(32G) for training in all our experiments. If you can provide some information about where or how did the code get stuck, perhaps we can help you analyze this problem. We are also working on improving this codebase for better efficiency.
Currently, since we use SMPL as a shape prior, which doesn't model hand gestures explicitly,  it's still challenging for ELICIT to recover the actual geometry of hands. We will try to address this problem in our future work.

**Comment by JACKYLUO1991** [comment]
![image](https://user-images.githubusercontent.com/21237742/218905447-dc875ce9-2081-4da4-92f3-5332b95979e5.png)
The display result of entering nvidia-smi when the program is stuck. This condition occurs every time it is run.

**Comment by huangyangyi** [comment]
> ![image](https://user-images.githubusercontent.com/21237742/218905447-dc875ce9-2081-4da4-92f3-5332b95979e5.png) The display result of entering nvidia-smi when the program is stuck. This condition occurs every time it is run.

Could you please tell us which line of code the program is stuck on? We have not encountered a problem like this. It seems that the program gets stuck in a DataParallel component (cnl_mlp) which only runs on secondary GPUs(1~3).

**Comment by hengfei-wang** [comment]
Hi,

I have the same problem. The training is stuck in Epoch 1 Iter 5420. And GPU status is the same as @JACKYLUO1991. Have you solved the problem?

<img width="458" alt="image" src="https://user-images.githubusercontent.com/39575336/219973548-3fb85aae-51ad-48d7-9ef0-378054b340eb.png">

**Comment by huangyangyi** [comment]
Hi @JACKYLUO1991, according to the feedback of @hengfei-wang, the custom op `grid_sample_3d` causes a stuck problem. Please pull [this commit](https://github.com/huangyangyi/ELICIT/commit/c4568049543899ecd74481bf2e2e8b06040cd4c7) and check whether it works for you. Again we thanks @hengfei-wang for his feedback!

**Comment by JACKYLUO1991** [comment]
@huangyangyi Fixed it...

**Comment by JACKYLUO1991** [comment]
@huangyangyi It seems that this is not the reason and the above problem still occurs.

**Comment by JACKYLUO1991** [comment]
@hengfei-wang Not really, did you find a solution? Could it be a GPU architecture problem, the author said he was using V100.

**Comment by hengfei-wang** [comment]
Hi, @JACKYLUO1991 

I can train successfully after revising the code according to the author. For your problem, I don't know why.
